version: "3.3"

services:
  api:
    image: baffedu/laravel:0.2-fpm
    volumes:
      - ${API_PATH}/supervisor.conf:/etc/supervisor.d/api.ini
      - ${API_PATH}:/var/www/html
      - ${MASTER_PATH}/logs:/var/log/uni
    environment:
      - VIRTUAL_HOST=${API_HOST}
      - APP_MAIN_DB=${APP_MAIN_DB}
      - APP_IMPORT_DB=${APP_IMPORT_DB}
  eip:
    image: baffedu/front:0.1
    volumes:
      - ${EIP_PATH}:/usr/share/nginx/html
    environment:
      - VIRTUAL_HOST=${EIP_HOST}
  finance:
    image: baffedu/front:0.1
    volumes:
      - ${FINANCE_PATH}:/usr/share/nginx/html
    environment:
      - VIRTUAL_HOST=${FINANCE_HOST}
  telesales:
    image: baffedu/front:0.1
    volumes:
      - ${TELESALES_PATH}:/usr/share/nginx/html
    environment:
      - VIRTUAL_HOST=${TELESALES_HOST}
  students:
    image: baffedu/front:0.1
    volumes:
      - ${STUDENTS_PATH}:/usr/share/nginx/html
    environment:
      - VIRTUAL_HOST=${STUDENTS_HOST}
  administration:
    image: baffedu/front:0.1
    volumes:
      - ${ADMINISTRATION_PATH}:/usr/share/nginx/html
    environment:
      - VIRTUAL_HOST=${ADMINISTRATION_HOST}

# when telnet other service, you may need to configure firewalld
# docker network create --driver=bridge --subnet=10.50.0.0/16 baffedu
networks:
  default:
    external:
      name: baffedu